- block:
  - name: apt install 
    shell: "sudo apt install -y {{ item.name }}"
    with_items: '{{ apt_packages }}'
  - name: apt cleanup
    shell: "sudo apt autoremove -y && sudo apt autoclean -y"
  tags:
    - apt
