- block:
  - name: checkout dotfiles
    git:
      repo: https://github.com/KEY60228/dotfiles.git
      dest: ~/dotfiles
  - name: create symblic links
    file:
      src: ~/dotfiles/{{ item }}
      dest: ~/{{ item }}
      state: link
      force: yes
    with_items: '{{ dot_files }}'
  tags:
    - dotfiles
