name: CI

on:
  push:

jobs:
  test:
    name: Install test
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: install
        run: bash ./init.sh
